trilogy-data/pytrilogy

preql/__init__.py, preql/core/exceptions.py, preql/core/models.py, preql/dialect/base.py, preql/dialect/duckdb.py, preql/dialect/enums.py, preql/dialect/sql_server.py, preql/executor.py, preql/parsing/parse_engine.py, requirements-test.txt, tests/adventureworks/conftest.py, tests/adventureworks/test_adventureworks.py, tests/engine/conftest.py, tests/engine/test_duckdb_executor.py
Update the direct query interface to better support interactive applications. Don't automatically paginate results; return raw SQL Alchemy result set for end-user handling. 
Assorted other fixes.
DuckDB backend to support in-memory integration testing.
=> Interactive App Support

preql/__init__.py
Trigger valid package release.
=> Edickinson version bump

.github/workflows/pythonpackage.yml, preql/__init__.py, preql/parsing/parse_engine.py, tests/adventureworks/test_adventureworks.py, tests/test_discovery_nodes.py, tests/test_query_processing.py
Fix min/max function assignments, allow them to work on dates.
=> Edickinson min max fixes

preql/__init__.py, preql/engine.py, requirements.txt
=> Fix type hints

preql/__init__.py
=> bumpverison

docs/website/docs/src/.vuepress/components/FreeformQueryComponent.vue, docs/website/docs/src/.vuepress/components/LoadingButton.vue, docs/website/docs/src/demo/readme.md, examples/duckdb_testing.py, preql/__init__.py, preql/core/models.py, preql/core/processing/utility.py, preql/parsing/parse_engine.py
=> Demo tweaks 4

docs/website/docs/src/demo/readme.md, preql/parsing/parse_engine.py
=> mypy fixes

docs/website/docs/src/.vuepress/components/constants.ts, docs/website/docs/src/demo/readme.md, examples/duckdb_testing.py, preql/__init__.py, preql/executor.py, requirements-test.txt
=> test fixes

docs/website/docs/src/.vuepress/components/constants.ts, preql/__init__.py, preql/core/enums.py, preql/core/functions.py, preql/core/models.py, preql/core/processing/nodes/base_node.py, preql/core/processing/nodes/merge_node.py, preql/core/processing/utility.py, preql/dialect/base.py, preql/dialect/duckdb.py, preql/parsing/parse_engine.py, tests/test_functions.py
Add in first batch of constant functions, like CURRENT_DATE, CURRENT_DATETIME, etc
=> Constant functions

preql/__init__.py, preql/core/functions.py, preql/core/processing/nodes/base_node.py, preql/executor.py
=> Feature 03 2024

.github/workflows/pythonpackage.yml, examples/duckdb_testing.py, preql/__init__.py, preql/core/enums.py, preql/core/models.py, preql/core/processing/nodes/select_node_v2.py, preql/dialect/base.py, preql/executor.py, preql/parsing/parse_engine.py, tests/engine/demo/test_demo_duckdb.py, tests/test_functions.py
We need to check for a group by when doing a direct select.
=> Fix group direct select post merge

.github/workflows/pythonpackage.yml, preql/__init__.py, preql/core/enums.py, preql/core/models.py, preql/core/processing/node_generators/basic_node.py, preql/parsing/parse_engine.py, tests/test_functions.py
Minor changes to ensure parsing works on latest pydantic.
=> Remove unsafe check

preql/__init__.py, preql/core/enums.py, preql/core/models.py, preql/core/processing/concept_strategies_v2.py, preql/core/processing/node_generators/group_node.py, preql/core/processing/nodes/base_node.py, preql/core/processing/nodes/group_node.py, preql/core/processing/nodes/select_node_v2.py, preql/core/processing/nodes/window_node.py, preql/core/processing/utility.py, preql/dialect/base.py, preql/dialect/common.py, preql/parsing/parse_engine.py, tests/complex/test_window_function_parsing.py, tests/engine/conftest.py, tests/engine/demo/test_demo_duckdb.py, tests/engine/test_duckdb_executor.py, tests/test_where_clause.py
Fix handling of constants that have been passed through functions - no longer safe to optimize away some checks.
Make behavior of adding a constant multiplication of a default aggregation consistent.
Introduce an alias function to prevent unexpected behavior when you select a concept as a rename.
=> Better constants

README.md, codecov.yml, examples/aoe2_debug.py, examples/community_debug.py, examples/debug_look.py, examples/derived_testing.py, examples/duckdb_testing.py, examples/duckdb_testing_two.py, examples/empty_environment_example.py, examples/persist_testing.py, preql/__init__.py, preql/core/enums.py, preql/core/functions.py, preql/core/models.py, preql/core/processing/concept_strategies_v2.py, preql/core/processing/node_generators/unnest_node.py, preql/core/query_processor.py, preql/dialect/base.py, preql/dialect/common.py, preql/dialect/postgres.py, preql/parsing/parse_engine.py, tests/engine/test_duckdb_executor.py, tests/test_functions.py, tests/test_select.py, tests/test_where_clause.py
- Extension of date functions
- Fix rendering of date functions on postgres backend
- Make generation of constants as concepts less aggressive (arrays only for now)
- Support for hiding columns from select output with "--" prefix
=> Postgres improvements

preql/__init__.py, preql/core/enums.py, preql/core/functions.py, preql/core/models.py, preql/core/processing/node_generators/basic_node.py, preql/core/processing/node_generators/filter_node.py, preql/core/processing/nodes/filter_node.py, preql/core/processing/nodes/group_node.py, preql/core/processing/nodes/merge_node.py, preql/core/processing/nodes/select_node_v2.py, preql/core/processing/utility.py, preql/dialect/base.py, preql/dialect/common.py, preql/dialect/postgres.py, preql/hooks/query_debugger.py, preql/parsing/parse_engine.py, tests/adventureworks/test_adventureworks.py, tests/conftest.py, tests/modeling/README.md, tests/modeling/conftest.py, tests/modeling/test_core_concepts.py, tests/test_declarations.py, tests/test_query_processing.py, tests/test_where_clause.py
Start to clean up and standardize handling of purpose assignments.
=> Better Eng Work

preql/__init__.py, preql/core/models.py, preql/core/processing/node_generators/basic_node.py, preql/core/processing/node_generators/select_node.py, preql/core/processing/node_generators/static_select_node.py, preql/core/processing/node_generators/window_node.py, preql/core/processing/nodes/select_node_v2.py, preql/dialect/base.py, preql/dialect/duckdb.py, preql/dialect/postgres.py, preql/executor.py, preql/parsing/parse_engine.py, tests/engine/conftest.py, tests/engine/test_postgres.py, tests/modeling/conftest.py, tests/modeling/test_core_concepts.py
Enable scalar transformations to be declared inline in datasource definition. (TODO: automatically assign).
Ex:
property order.order_date date;
property order.order_month date;
datasource x (
date:order_date,
date_trunc(order_date, month):order_month
)
Misc bug fixes
=> additional fixes

preql/__init__.py, preql/core/models.py, preql/dialect/duckdb.py, preql/parsing/parse_engine.py, tests/conftest.py, tests/engine/demo/test_demo_duckdb.py, tests/modeling/test_core_concepts.py, tests/test_models.py
Revert filtered concept derivation until circular dependencies can be figure out; fix current_datetime in duckdb.
=> 2024 filter fixes

README.md, preql/__init__.py, preql/core/enums.py, preql/core/functions.py, preql/core/models.py, preql/core/processing/concept_strategies_v3.py, preql/core/processing/node_generators/filter_node.py, preql/core/processing/node_generators/group_node.py, preql/core/processing/node_generators/select_node.py, preql/core/processing/node_generators/unnest_node.py, preql/core/processing/nodes/base_node.py, preql/core/processing/nodes/merge_node.py, preql/core/processing/nodes/select_node_v2.py, preql/dialect/base.py, preql/parsing/parse_engine.py, requirements-test.txt, tests/engine/demo/test_demo_duckdb.py, tests/modeling/google_analytics/all_sites.preql, tests/modeling/google_analytics/daily_visits.preql, tests/modeling/google_analytics/generic.preql, tests/modeling/google_analytics/test_sane_ga_rendering.py, tests/test_functions.py, tests/test_query_processing.py
Fix some silliness with generated queries under new pattern.
1. fetch constants first, so a subsequent concept fetch that gets all optional can complete the graph and early exit
2. remove redundant optional fetch for a group node if the group node already includes all optional concepts.
=> May changes

preql/__init__.py, preql/constants.py, preql/core/models.py, preql/core/processing/concept_strategies_v3.py, preql/parsing/parse_engine.py, preql/parsing/render.py, tests/modeling/test_complex.py, tests/rendering/test_rendering.py
Clean up some ordering issues related to complex rowset fetches.
Better definition of virtual types.
Enable virtual types to render back to raw code.
=> post-rowset fixes

preql/__init__.py, preql/core/models.py, preql/core/processing/node_generators/common.py, preql/core/processing/node_generators/group_node.py, preql/core/processing/node_generators/group_to_node.py, preql/core/processing/node_generators/rowset_node.py, preql/core/processing/node_generators/window_node.py, preql/core/processing/nodes/merge_node.py, preql/parsing/parse_engine.py, tests/engine/demo/test_demo_duckdb.py
Fix propagation of keys to rowsets;
Redefine keys/grains of a rowset to reflect the rowset
Fix extra keys included in join (drop properties when key is also present)
=> May changes two

preql/__init__.py, preql/core/functions.py, preql/core/models.py, preql/dialect/duckdb.py, preql/parsing/parse_engine.py, tests/engine/test_duckdb_executor.py, tests/rendering/test_rendering.py, tests/test_functions.py
Fixes to handling of types to arrays.
Fixes to rendering of some duckdb date functions.
=> May third release

.github/workflows/pythonpackage.yml, README.md, preql/__init__.py, preql/core/models.py, preql/core/processing/concept_strategies_v3.py, preql/core/processing/node_generators/rowset_node.py, preql/core/processing/node_generators/window_node.py, preql/core/processing/nodes/merge_node.py, preql/core/query_processor.py, preql/parsing/parse_engine.py, preql/scripts/trilogy.py, requirements-test.txt, tests/engine/test_bigquery.py, tests/engine/test_duckdb_executor.py, tests/generators/conftest.py, tests/generators/test_merge_node.py, tests/scripts/test_trilogy.py, tests/test_functions.py, tests/test_where_clause.py
Early exit optimizations on window nodes need to account for the fact that the window always needs one CTE to enable future use in group by. 
Add in formatting/run as subcommands to trilogy CLI
=> Fix window/rowset issues

preql/__init__.py, preql/core/functions.py, preql/core/models.py, preql/core/processing/concept_strategies_v3.py, preql/core/processing/node_generators/basic_node.py, preql/core/processing/node_generators/common.py, preql/core/processing/node_generators/concept_merge.py, preql/core/processing/node_generators/multiselect_node.py, preql/core/processing/node_generators/select_node.py, preql/core/processing/nodes/base_node.py, preql/core/processing/nodes/group_node.py, preql/core/processing/nodes/merge_node.py, preql/parsing/common.py, preql/parsing/parse_engine.py, tests/complex/test_window_function_parsing.py, tests/engine/demo/test_demo_duckdb.py, tests/engine/demo/test_demo_duckdb_multi_table.py, tests/engine/test_postgres.py, tests/engine/test_snowflake.py, tests/generators/test_merge_concept_node.py, tests/modeling/google_analytics/daily_visits.preql, tests/modeling/google_analytics/test_sane_ga_rendering.py, tests/modeling/tcp_ds/test_queries.py, tests/modeling/test_complex.py, tests/modeling/test_core_concepts.py, tests/persistence/test_basic_persistence.py, tests/test_partial_handling.py
Clean up ordering of fetching for basic nodes to make more natural queries.
=> Cleaner query derivation

preql/__init__.py, preql/core/models.py, preql/core/processing/node_generators/select_node.py, preql/core/processing/nodes/select_node_v2.py, tests/generators/test_select_node_generator.py, tests/test_functions.py
Fix up some issues with constant resolution introduced in last round of fixes.
=> Better Constant Handling

preql/__init__.py, preql/core/models.py, preql/core/processing/nodes/merge_node.py, preql/core/processing/nodes/select_node_v2.py, preql/parsing/common.py, tests/adventureworks/test_adventureworks.py, tests/engine/test_duckdb_executor.py, tests/generators/test_merge_node.py, tests/modeling/google_analytics/test_sane_ga_rendering.py, tests/test_partial_handling.py
Aggregate Wrapper information could be lost when inhering select grain
=> Add testing around aggregate wrapper handling

preql/__init__.py, preql/core/models.py, preql/core/processing/concept_strategies_v3.py, preql/core/processing/node_generators/common.py, preql/core/processing/node_generators/filter_node.py, preql/dialect/base.py, preql/dialect/bigquery.py, preql/dialect/snowflake.py, preql/parsing/common.py, tests/engine/test_duckdb_executor.py, tests/modeling/aggregates/test_cardinality.py
Fix a response issue for a with_select_grain call + remove unnecessary deepcopies.
=> Case statement tuple fix

README.md, trilogy/__init__.py, trilogy/core/models.py, trilogy/dialect/base.py, trilogy/dialect/bigquery.py
Fix some issues with refactored aliasing.
=> July tweaks

tests/engine/demo/conftest.py, tests/engine/demo/test_demo_duckdb.py, trilogy/__init__.py, trilogy/core/models.py, trilogy/core/processing/node_generators/common.py, trilogy/core/processing/node_generators/rowset_node.py, trilogy/core/processing/nodes/base_node.py, trilogy/core/processing/nodes/merge_node.py, trilogy/parsing/parse_engine.py
Fix issue with discovery of additional merge concepts for directly nested function references
Minimize materialization of non-output concepts in rowsets to reduce query size.
=> Rwoset Query Minimization; Discovery of Merge Concept Bugfix

codecov.yml, tests/modeling/tcp_ds_duckdb/date.preql, tests/modeling/tcp_ds_duckdb/item.preql, tests/modeling/tcp_ds_duckdb/query12.preql, tests/modeling/tcp_ds_duckdb/test_queries.py, tests/modeling/tcp_ds_duckdb/web_sales.preql, tests/test_parsing.py, trilogy/__init__.py, trilogy/core/models.py, trilogy/core/optimization.py, trilogy/parsing/parse_engine.py
Avoid us inlining a ds if it is already a source (this will require us to build out better aliasing to support).
Add in between parsing support.
=> July fixes three

setup.py, trilogy/__init__.py
The .lark syntax file isn't included in the pypi distribution.
=> Include lark file

tests/modeling/tcp_ds_duckdb/test_queries.py, tests/test_parsing.py, trilogy/__init__.py, trilogy/core/models.py, trilogy/parsing/parse_engine.py
The LazyEnvironment class was missing one attribute to pass through to parent, making instantiation of public repo very slow.
Add some additional tests too.
=> Fix lazy startup timing

tests/engine/test_duckdb.py, tests/engine/test_presto.py, tests/optimization/pushdown.preql, tests/optimization/test_optimization.py, tests/optimization/test_pushdown_optimization.py, tests/rendering/test_rendering.py, tests/test_datatypes.py, trilogy/__init__.py, trilogy/constants.py, trilogy/core/functions.py, trilogy/core/models.py, trilogy/core/optimization.py, trilogy/core/optimizations/predicate_pushdown.py, trilogy/dialect/base.py, trilogy/dialect/presto.py, trilogy/parsing/parse_engine.py, trilogy/parsing/render.py, trilogy/parsing/trilogy.lark
- Numeric Support
- Improved predicate pushdown
=> August dev work

tests/engine/demo/test_demo_duckdb.py, tests/engine/test_duckdb.py, tests/rendering/test_rendering.py, tests/test_statements.py, trilogy/__init__.py, trilogy/core/models.py, trilogy/core/processing/node_generators/select_node.py, trilogy/parsing/parse_engine.py, trilogy/parsing/render.py, trilogy/parsing/trilogy.lark
Provide the ability to bind conditions/filters directly to datasource declarations. Useful to avoid queries in a case where the raw data always needs to be filtered on a condition.
=> Filtered Datasources

README.md, tests/engine/demo/test_demo_duckdb.py, tests/modeling/tcp_ds_duckdb/call_center.preql, tests/modeling/tcp_ds_duckdb/catalog_returns.preql, tests/modeling/tcp_ds_duckdb/catalog_sales.preql, tests/modeling/tcp_ds_duckdb/customer.preql, tests/modeling/tcp_ds_duckdb/query16.preql, tests/modeling/tcp_ds_duckdb/test_queries.py, tests/modeling/tcp_ds_duckdb/warehouse.preql, tests/optimization/test_constant_optimization.py, tests/optimization/test_optimization.py, trilogy/core/models.py, trilogy/core/optimization.py, trilogy/core/optimizations/predicate_pushdown.py, trilogy/core/processing/utility.py, trilogy/core/query_processor.py, trilogy/dialect/base.py
=> modeling fixes

tests/modeling/tcp_ds_duckdb/catalog_returns.preql, tests/modeling/tcp_ds_duckdb/query16.preql, tests/modeling/tcp_ds_duckdb/test_queries.py, tests/test_parsing.py, tests/test_where_clause.py, trilogy/__init__.py, trilogy/core/README.md, trilogy/core/enums.py, trilogy/core/functions.py, trilogy/core/models.py, trilogy/core/optimizations/predicate_pushdown.py, trilogy/core/processing/concept_strategies_v3.py, trilogy/core/processing/node_generators/common.py, trilogy/core/processing/node_generators/filter_node.py, trilogy/core/processing/nodes/group_node.py, trilogy/core/processing/utility.py, trilogy/core/query_processor.py, trilogy/dialect/base.py, trilogy/dialect/bigquery.py, trilogy/dialect/duckdb.py, trilogy/dialect/postgres.py, trilogy/dialect/presto.py, trilogy/dialect/snowflake.py, trilogy/dialect/sql_server.py, trilogy/parsing/common.py, trilogy/parsing/parse_engine.py, trilogy/parsing/trilogy.lark
Mix of small fixes, mostly around struct handling
- Fixed condition pushdown for queries that output all aggregates
- Added constant struct declaration support
- Updated structs behavior so they represent implicit namespaces and all child concepts are promoted
- Added basic having clause support to filter on aggregates in filter nodes more cleanly
=> query_16_support

tests/engine/test_presto.py, trilogy/__init__.py, trilogy/core/enums.py, trilogy/core/models.py, trilogy/dialect/base.py, trilogy/dialect/common.py, trilogy/dialect/presto.py
Fix behavior of unnest queries w/ presto
=> presto unnest rendering fixes

tests/modeling/tcp_ds_duckdb/catalog_sales.preql, tests/modeling/tcp_ds_duckdb/query16.preql, tests/modeling/tcp_ds_duckdb/test_queries.py, trilogy/__init__.py, trilogy/constants.py, trilogy/core/models.py, trilogy/core/processing/node_generators/filter_node.py, trilogy/core/processing/nodes/group_node.py, trilogy/core/processing/utility.py, trilogy/core/query_processor.py, trilogy/dialect/base.py, trilogy/dialect/duckdb.py, trilogy/parsing/parse_engine.py
Fix some sharp edges with mixed aggregate/scalar filter clauses.
=> aggregate filter handling improvements

tests/rendering/test_rendering.py, trilogy/__init__.py, trilogy/parsing/render.py
Case statement rendering was broken. Fix and add test.
=> Fix case rendering

tests/engine/test_duckdb.py, tests/test_parsing.py, trilogy/__init__.py, trilogy/parsing/parse_engine.py, trilogy/parsing/trilogy.lark
Micro-fix; enable parsing the empty string '';
=> Empty String Parsing

requirements-test.txt, requirements.txt, tests/modeling/tpc_ds_duckdb/query06.preql, tests/modeling/tpc_ds_duckdb/zquery06.log, tests/test_enums.py, tests/test_select.py, trilogy/__init__.py, trilogy/core/enums.py, trilogy/core/models.py, trilogy/parsing/parse_engine.py
Remove a noisy print.
Add some better enum handling.
Move validation of select onto a method of the select.
=> minor tweaks

tests/modeling/tpc_ds_duckdb/address.preql, tests/modeling/tpc_ds_duckdb/customer.preql, tests/modeling/tpc_ds_duckdb/query30.preql, tests/modeling/tpc_ds_duckdb/test_queries.py, tests/modeling/tpc_ds_duckdb/web_returns.preql, tests/modeling/tpc_ds_duckdb/zquery07.log, tests/modeling/tpc_ds_duckdb/zquery30.log, tests/rendering/test_rendering.py, tests/test_executor.py, tests/test_parsing.py, trilogy/__init__.py, trilogy/core/models.py, trilogy/executor.py, trilogy/parsing/parse_engine.py, trilogy/parsing/render.py, trilogy/parsing/trilogy.lark
=> query_30_support

trilogy/__init__.py, trilogy/core/models.py
Tiny fix; use the proper method to assign a concept.
=> model definition fixes

tests/rendering/test_rendering.py, trilogy/__init__.py, trilogy/core/models.py, trilogy/dialect/base.py, trilogy/parsing/parse_engine.py, trilogy/parsing/render.py
Make basic math functions take arbitrary numbers of arguments.
=> Expanded functions

tests/modeling/tpc_ds_duckdb/test_non_benchmark_queries.py, tests/test_functions.py, trilogy/__init__.py, trilogy/core/processing/node_generators/window_node.py, trilogy/parsing/common.py
Was inheriting from parent type; should be int for certain types (rank, row_number, etc)
=> fix datatype for window functions that output integers

.github/workflows/pythonpackage.yml, .gitignore, tests/modeling/tpc_ds_duckdb/conftest.py, tests/profiling/conftest.py, trilogy/__init__.py, trilogy/dialect/base.py
Matrix over 3.11 as well as 3.12, fix compat issues.
=> publish version check

tests/rendering/test_rendering.py, trilogy/__init__.py, trilogy/parsing/render.py
- Fix datasource rendering with empty grain
- Fix parenthetical rendering when function
=> More Render Fixes

tests/test_parsing.py, tests/test_query_render.py, trilogy/__init__.py, trilogy/authoring/__init__.py, trilogy/core/models/environment.py, trilogy/core/processing/nodes/group_node.py, trilogy/dialect/bigquery.py, trilogy/dialect/duckdb.py, trilogy/dialect/enums.py, trilogy/dialect/presto.py, trilogy/dialect/sql_server.py, trilogy/executor.py, trilogy/parsing/parse_engine.py, trilogy/render.py
Support resolving imports from alternative locations. For now, support resolving from a dictionary. 
Future cases can include resolving from cloud addresses (GCS, S3, etc)
=> Expanded Import IO Resolution

tests/engine/test_duckdb.py, tests/test_query_render.py, trilogy/__init__.py, trilogy/engine.py
Expose the commit() method on sqlalchemy connections.
=> Add typing for commits

trilogy/__init__.py
=> version bump

tests/engine/test_duckdb.py, trilogy/__init__.py, trilogy/core/models/build.py, trilogy/core/models/execute.py, trilogy/core/processing/concept_strategies_v3.py, trilogy/parsing/parse_engine.py
Closes https://github.com/trilogy-data/pytrilogy/issues/257
The expression tuple parser has been broken for some time, since most tuple evaluations in tests take the constant path. Fix and add test case.
=> Tuple parsing fix

tests/engine/test_duckdb.py, tests/stdlib/test_basic_import.py, tests/test_parsing.py, trilogy/__init__.py, trilogy/core/models/author.py, trilogy/core/models/core.py, trilogy/dialect/base.py, trilogy/parsing/parse_engine.py, trilogy/std/dashboard.preql, trilogy/std/date.preql, trilogy/std/geography.preql, trilogy/std/money.preql
Implement a basic standard library (batteries included, starting with types).
=> Add Standard Lib

trilogy/__init__.py
wheel didn't include stdlib files because it was looking for python directories; add a init for now.
=> Std lib polish

trilogy/__init__.py, trilogy/std/geography.preql
Add a usa shortname to stdlib.
=> Micro Release - Add Shortname

tests/engine/test_duckdb.py, tests/modeling/tpc_ds_duckdb/test_non_benchmark_queries.py, tests/test_environment.py, trilogy/__init__.py, trilogy/core/enums.py, trilogy/core/environment_helpers.py, trilogy/core/models/author.py, trilogy/core/models/environment.py, trilogy/dialect/duckdb.py
DuckDB date function used an invalid syntax date().
Add in truncation helpers as well.
=> DuckDB Date Fixes

tests/test_derived_concepts.py, tests/test_metadata.py, trilogy/__init__.py, trilogy/core/environment_helpers.py, trilogy/parsing/parse_engine.py
Some overly aggressive code for commenting on imports tainted LLM completion. Removing for now until we find a better approach.
Fix up trait population for some types.
=> Better Descriptions + Traits

tests/test_functions.py, tests/test_metadata.py, tests/test_typing.py, trilogy/__init__.py, trilogy/core/enums.py, trilogy/core/functions.py, trilogy/core/models/build.py, trilogy/dialect/base.py, trilogy/dialect/bigquery.py, trilogy/parsing/parse_engine.py, trilogy/parsing/trilogy.lark
=> Fix List Typecasts

tests/engine/demo/conftest.py, tests/modeling/ncaa/adhoc06.preql, tests/modeling/ncaa/test_ncaa.py, tests/modeling/tpc_ds_duckdb/zquery_timing_amd64-intel64_family_6_model_183_stepping_1_genuineintel-16.log, tests/test_parsing.py, trilogy/__init__.py, trilogy/core/functions.py, trilogy/core/models/author.py, trilogy/core/models/build.py, trilogy/core/models/execute.py, trilogy/parsing/common.py, trilogy/parsing/parse_engine.py
Weird intermittent pydantic errors seem to happen around these. Remove to see if it fixes. Model validation is cleaner anyway.
=> Remove __init__ Sub-Classing

tests/modeling/aggregates/test_group_by.py, tests/modeling/tpc_ds_duckdb/zquery_timing_amd64-intel64_family_6_model_183_stepping_1_genuineintel-16.log, trilogy/core/enums.py, trilogy/core/models/author.py, trilogy/core/processing/concept_strategies_v3.py, trilogy/core/processing/discovery_node_factory.py, trilogy/core/processing/discovery_utility.py, trilogy/parsing/common.py
Followup on previous refactor to make group to not a special case in codebase.
=> Align group to handlign with general derivation

tests/modeling/hackernews/adhoc04.preql, tests/modeling/hackernews/hackernews.preql, tests/modeling/hackernews/test_hackernews_queries.py, trilogy/__init__.py, trilogy/dialect/snowflake.py, trilogy/parsing/parse_engine.py, trilogy/std/date.preql, trilogy/std/geography.preql, trilogy/std/money.preql, trilogy/std/net.preql
Snowflake needs CTE names to be quoted to if we will quote the identifiers.
=> Snowflake Fix

tests/engine/test_duckdb.py, tests/modeling/ncaa/adhoc07.preql, tests/modeling/ncaa/game_event.preql, tests/modeling/ncaa/test_ncaa.py, tests/modeling/ncaa/top_player_dashboard.preql, tests/modeling/tpc_ds_duckdb/zquery_timing_amd64-intel64_family_6_model_183_stepping_1_genuineintel-16.log, trilogy/__init__.py, trilogy/core/enums.py, trilogy/core/functions.py, trilogy/core/models/build.py, trilogy/core/processing/node_generators/window_node.py, trilogy/dialect/base.py, trilogy/parsing/common.py, trilogy/parsing/parse_engine.py, trilogy/std/net.preql
Window grain calculations pulled in too many concepts for anonymous order by.
Also fix constants being able to be cast to traits.
=> Window Grain Fixes

tests/engine/test_bigquery.py, tests/modeling/test_arrays.py, tests/modeling/tpc_ds_duckdb/zquery_timing_amd64-intel64_family_6_model_183_stepping_1_genuineintel-16.log, tests/rendering/test_rendering.py, tests/test_functions.py, trilogy/__init__.py, trilogy/authoring/__init__.py, trilogy/core/enums.py, trilogy/core/functions.py, trilogy/core/models/author.py, trilogy/core/models/build.py, trilogy/core/models/core.py, trilogy/core/processing/utility.py, trilogy/dialect/base.py, trilogy/dialect/duckdb.py, trilogy/parsing/parse_engine.py, trilogy/parsing/render.py, trilogy/parsing/trilogy.lark
Do a pass on better array handling.
Added functions:
- array_unique
- array_sum
- array_sort
- array_agg
- array_transform
Consolidated list/array datatype overlap. We can reintroduce list at some point if we want to differentiate (static vs mixed types?)
=> Array Features

tests/engine/test_duckdb.py, tests/modeling/tpc_ds_duckdb/zquery_timing_amd64-intel64_family_6_model_183_stepping_1_genuineintel-16.log, tests/test_parsing.py, trilogy/__init__.py, trilogy/core/enums.py, trilogy/core/internal.py, trilogy/core/models/author.py, trilogy/core/models/build.py, trilogy/core/statements/execute.py, trilogy/dialect/base.py, trilogy/executor.py, trilogy/parsing/parse_engine.py
SHOW CONCEPTS is something LLMs like to use. Make it work.
=> Fix show concepts statement

tests/test_parse_engine.py, trilogy/__init__.py, trilogy/parsing/parse_engine.py, trilogy/parsing/trilogy.lark
Start adding more helpful parser errors.
=> Better Errors

tests/modeling/gcat/launch.preql, tests/modeling/gcat/platform.preql, tests/modeling/gcat/test_gcat.py, tests/modeling/gcat/vehicle.preql, tests/modeling/tpc_ds_duckdb/zquery12.log, tests/modeling/tpc_ds_duckdb/zquery20.log, tests/modeling/tpc_ds_duckdb/zquery_timing_amd64-intel64_family_6_model_183_stepping_1_genuineintel-16.log, trilogy/__init__.py, trilogy/core/processing/node_generators/node_merge_node.py, trilogy/core/processing/utility.py
When a nullable column is on the right side of a join, we should use a full not a left-outer.
=> Nullability Fixes

tests/modeling/gcat/test_gcat.py, tests/modeling/nyc_citibike/test_nyc.py, tests/modeling/tpc_ds_duckdb/zquery12.log, tests/modeling/tpc_ds_duckdb/zquery16.log, tests/modeling/tpc_ds_duckdb/zquery20.log, tests/modeling/tpc_ds_duckdb/zquery21.log, tests/modeling/tpc_ds_duckdb/zquery99.log, tests/modeling/tpc_ds_duckdb/zquery_timing_amd64-intel64_family_6_model_183_stepping_1_genuineintel-16.log, trilogy/__init__.py, trilogy/core/processing/utility.py, trilogy/std/geography.preql, trilogy/std/net.preql
The last nullability fixes exposed a bug in aggregate node generation that causes it to mark concepts as nullable when they are not; fixed that up and clarified join decision tree.
=> Nullability Fixes Two

tests/complex/test_structs.py, trilogy/__init__.py, trilogy/core/functions.py, trilogy/core/models/author.py, trilogy/core/models/core.py, trilogy/parsing/parse_engine.py
Output types of attribute access functions were wrong.
=> attribute access type fixes

trilogy/parsing/parse_engine.py
This is not always a token; sometimes it is null.
=> parse error fix
